"""empty message

Revision ID: 52cea92a78d4
Revises: 747083fe87ba
Create Date: 2025-04-02 19:47:33.375287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52cea92a78d4'
down_revision = '747083fe87ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('post_code', sa.String(), nullable=False))
        batch_op.alter_column('total',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('total',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('post_code')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
